/*
 * Demonstrate how to set up a timer that, on expiry,
 * sends us a pulse.  This example sets the first
 * expiry to 1.5 seconds and the repetition interval
 * to 1.5 seconds.
 */




#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <sys/netmgr.h>
#include <sys/neutrino.h>

#include <errno.h>


char *progname = "timer_per1.c";

enum states { State0, State1, State2};

#define MY_PULSE_CODE   _PULSE_CODE_MINAVAIL

// MsgReceive() writes the received data into one buffer.
// A union lets the same buffer represent either a QNX pulse or another
// message type, because only one of them is received at a time.
typedef union
{
	struct _pulse pulse;   // QNX pulse data, including code and sender details

	// Add other message structures here if this channel also receives messages.
	// Example: struct my_data_message data;
} my_message_t;


int main(int argc, char *argv[])
{
	printf("##########################################################\n");
	printf("#                                                        #\n");
	printf("#              EXAMPLE Code                              #\n");
	printf("#                                                        #\n");
	printf("#         QNX implementation of POSIX timers             #\n");
	printf("#                                                        #\n");
	printf("#  Process runs a simple state machine {states: 0,1,2}   #\n");
	printf("#                                                        #\n");
	printf("##########################################################\n");

	enum states CurrentState = State0; // Current state of the state machine

	// Describes how QNX should notify us when the timer expires.
	struct sigevent event;

	// Stores the first expiry time and the repeating interval.
	struct itimerspec itime;

	// Handle used by the OS to identify the created timer.
	timer_t timer_id;

	// ID of the channel that receives pulses and messages.
	int chid;

	// Return value from MsgReceive(): 0 for a pulse, >0 for a message.
	int rcvid;

	// Shared receive buffer. Here it contains msg.pulse when a pulse arrives.
	my_message_t msg;

	// Create the channel on which this process will receive timer pulses.
	chid = ChannelCreate(0);

	// Select pulse notification instead of a signal or thread callback.
	event.sigev_notify = SIGEV_PULSE;

	// Attach a connection to our own channel.
	// The timer uses this connection to deliver each pulse back to this process.
	event.sigev_coid = ConnectAttach(ND_LOCAL_NODE, 0, chid, _NTO_SIDE_CHANNEL, 0);
	if (event.sigev_coid == -1)
	{
	   printf(stderr, "%s:  couldn't ConnectAttach to self!\n", progname);
	   perror(NULL);
	   exit(EXIT_FAILURE);
	}
	// Use the current thread priority for the timer pulse.
	// getprio(0) was used in older QNX versions but is deprecated in QNX 7.
	struct sched_param th_param;
	pthread_getschedparam(pthread_self(), NULL, &th_param);
	event.sigev_priority = th_param.sched_curpriority;

	// Application-defined code used to distinguish this timer's pulse
	// from other pulses that may arrive on the same channel.
	event.sigev_code = MY_PULSE_CODE;

	// Create the timer using CLOCK_REALTIME and bind it to event.
	// timer_id receives the handle needed to start or modify the timer.
	if (timer_create(CLOCK_REALTIME, &event, &timer_id) == -1)
	{
	   printf (stderr, "%s:  couldn't create a timer, errno %d\n", progname, errno);
	   perror (NULL);
	   exit (EXIT_FAILURE);
	}

	// it_value specifies when the timer expires for the first time.
	itime.it_value.tv_sec = 1;              // 1 second
	itime.it_value.tv_nsec = 500000000;     // 0.5 second

	// it_interval specifies the period after the first expiry.
	// A zero interval would make this a one-shot timer.
	itime.it_interval.tv_sec = 1;           // 1 second
	itime.it_interval.tv_nsec = 500000000;  // 0.5 second

	// Arm the timer. The first pulse arrives after 1.5 seconds,
	// then another pulse arrives every 1.5 seconds.
	timer_settime(timer_id, 0, &itime, NULL);

	int Runtimes = 10; // Number of timer expiries to process
	int counter = 0;    // Counts received timer pulses

	for (counter=0; counter < Runtimes; counter++)
	{
		// Block until a message or pulse arrives. The received bytes are stored
		// in the union msg; for a pulse, access them through msg.pulse.
	   rcvid = MsgReceive(chid, &msg, sizeof(msg), NULL);

	   // MsgReceive() returns 0 for a pulse and a positive ID for a message.
	   if (rcvid == 0)
	   {
		   // Check that this pulse was generated by our timer.
		   if (msg.pulse.code == MY_PULSE_CODE)
			{
				// Here we implement a simple state machine
				printf("In state = %d\n", CurrentState);
				switch (CurrentState)
				{
					case 0:
						 // do some work;
						 CurrentState = State1;
						 break;
					case 1:
						 // do some work;
						 CurrentState = State2;
						 break;
					case 2:
						 // do some work;
						 CurrentState = State0;
						 break;
				}
				fflush(stdout); // make sure we print to the screen
			}
			// else other pulses ...
	   }
	   // else other messages ...
	}

	printf("\nSwitch statement got called %d times\n", counter);

	printf("All good. Main Terminated...\n\n");
	return EXIT_SUCCESS;
}

